llm:
  model: "gpt-4o"
  temperature: 0.3
  max_tokens: 10000

agents:
  requirements_analyst:
    max_execution_time: 300
    memory: true
  
  technical_architect:
    max_execution_time: 400
    memory: true
    
  business_analyst:
    max_execution_time: 300
    memory: true
    
  compliance_officer:
    max_execution_time: 200
    memory: true
    
  cost_estimator:
    max_execution_time: 250
    memory: true
    
  rfp_writer:
    max_execution_time: 500
    memory: true

project_templates:
  data_warehouse:
    base_template: "data_warehouse/enterprise_dw_template.md"
    technical_specs: "data_warehouse/dw_technical_specs.md"
  
  dotnet_application:
    base_template: "dotnet_application/custom_app_template.md"
    technical_specs: "dotnet_application/dotnet_technical_specs.md"

cost_benchmarks:
  data_warehouse:
    small: 150000
    medium: 500000
    large: 1500000
  
  dotnet_application:
    small: 75000
    medium: 250000
    large: 750000
    
  cloud_migration:
    small: 100000
    medium: 350000
    large: 1000000
